/**
 * lib/graph/query.ts
 *
 * Client-side graph queries using pre-built graph data embedded at build time.
 * For production: replace with DuckDB-WASM or server-side Parquet queries.
 *
 * The graph data is generated by:
 *   python3 scripts/graph/build_graph.py
 * which writes data/graph/graph-data.json (imported below at build time).
 */

import graphData from "../../data/graph/graph-data.json"

// ── Types ─────────────────────────────────────────────────────────────────────

export type EntityType = "Policy" | "Country" | "Domain" | "Indicator" | "DataSource"

export interface Entity {
  id: string
  type: EntityType
  label: string
  label_de: string
  /** Parsed from the JSON string stored in Parquet */
  properties: Record<string, unknown>
  created_at: string
}

export interface Relation {
  subject_id: string
  predicate: string
  object_id: string
  weight: number
  source_id?: string | null
  valid_from?: string | null
  valid_to?: string | null
  /** Parsed from the JSON string stored in Parquet */
  properties?: Record<string, unknown>
  created_at: string
}

// ── Internal helpers ──────────────────────────────────────────────────────────

type RawEntity = Omit<Entity, "properties"> & { properties: string }
type RawRelation = Omit<Relation, "properties"> & { properties: string }

function parseEntity(raw: RawEntity): Entity {
  return {
    ...raw,
    properties: raw.properties ? JSON.parse(raw.properties) : {},
  }
}

function parseRelation(raw: RawRelation): Relation {
  return {
    ...raw,
    properties: raw.properties ? JSON.parse(raw.properties) : {},
  }
}

// Parse once at module load (graph is static at build time)
const entities: Entity[] = (graphData.entities as RawEntity[]).map(parseEntity)
const relations: Relation[] = (graphData.relations as RawRelation[]).map(parseRelation)

const entityById = new Map<string, Entity>(entities.map((e) => [e.id, e]))

// ── Public API ────────────────────────────────────────────────────────────────

/** Look up any entity by its fully-qualified ID (e.g. "policy:transit-density") */
export function getEntity(id: string): Entity | undefined {
  return entityById.get(id)
}

/** All entities of a given type */
export function getEntitiesByType(type: EntityType): Entity[] {
  return entities.filter((e) => e.type === type)
}

/** All relations matching a predicate */
export function getRelationsByPredicate(predicate: string): Relation[] {
  return relations.filter((r) => r.predicate === predicate)
}

/**
 * Returns Policy entities that address the given domain.
 * @param domainId  bare slug, e.g. "housing"  —OR—  full id "domain:housing"
 */
export function getPoliciesForDomain(domainId: string): Entity[] {
  const id = domainId.startsWith("domain:") ? domainId : `domain:${domainId}`
  const policyIds = relations
    .filter((r) => r.predicate === "addresses" && r.object_id === id)
    .map((r) => r.subject_id)
  return policyIds.flatMap((pid) => (entityById.get(pid) ? [entityById.get(pid)!] : []))
}

/**
 * Returns Country entities where the policy has been implemented as an example.
 * @param policyId  bare slug, e.g. "digital-citizen-account"  —OR—  full id
 */
export function getCountriesForPolicy(policyId: string): Entity[] {
  const id = policyId.startsWith("policy:") ? policyId : `policy:${policyId}`
  const countryIds = relations
    .filter((r) => r.predicate === "implemented_in" && r.subject_id === id)
    .map((r) => r.object_id)
  return countryIds.flatMap((cid) => (entityById.get(cid) ? [entityById.get(cid)!] : []))
}

/**
 * Returns Indicator entities that measure the given domain.
 * @param domainId  bare slug or full id
 */
export function getIndicatorsForDomain(domainId: string): Entity[] {
  const id = domainId.startsWith("domain:") ? domainId : `domain:${domainId}`
  const indicatorIds = relations
    .filter((r) => r.predicate === "measures" && r.subject_id === id)
    .map((r) => r.object_id)
  return indicatorIds.flatMap((iid) => (entityById.get(iid) ? [entityById.get(iid)!] : []))
}

/**
 * Returns policies related to the given policy via enables/conflicts_with.
 * @param policyId  bare slug or full id
 */
export function getRelatedPolicies(
  policyId: string
): Array<{ policy: Entity; relation: string }> {
  const id = policyId.startsWith("policy:") ? policyId : `policy:${policyId}`
  const connected = relations
    .filter(
      (r) =>
        (r.predicate === "enables" || r.predicate === "conflicts_with") &&
        (r.subject_id === id || r.object_id === id)
    )
    .flatMap((r) => {
      const otherId = r.subject_id === id ? r.object_id : r.subject_id
      const other = entityById.get(otherId)
      if (!other) return []
      return [{ policy: other, relation: r.predicate }]
    })
  return connected
}

/**
 * Returns has_value relations for the given indicator, optionally filtered by year.
 */
export function getIndicatorValues(
  indicatorId: string,
  year?: number
): Array<{ country: Entity; value: number; year: number; unit: string }> {
  const id = indicatorId.startsWith("indicator:") ? indicatorId : `indicator:${indicatorId}`
  return relations
    .filter((r) => r.predicate === "has_value" && r.subject_id === id)
    .flatMap((r) => {
      const country = entityById.get(r.object_id)
      if (!country) return []
      const props = r.properties ?? {}
      const rowYear = props.year as number
      if (year !== undefined && rowYear !== year) return []
      return [
        {
          country,
          value: props.value as number,
          year: rowYear,
          unit: (props.unit as string) ?? "",
        },
      ]
    })
    .sort((a, b) => a.value - b.value)
}

/** Graph metadata */
export const graphMeta = {
  generatedAt: graphData.generated_at,
  entityCount: entities.length,
  relationCount: relations.length,
}
